name: Deploy Apps

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: "18"
  AZURE_WEBAPP_PACKAGE_PATH: "."
jobs:
  build-apps:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@main
      - name: Build App 1
        run: |
          cd app1
          npm install
          npm run build
      - name: Zip App
        run: |
          cd app1/build
          zip -r app1.zip .
      - name: Build App 2
        run: |
          cd app2
          npm install
          npm run build
      - name: Zip App
        run: |
          cd app2/build
          zip -r app2.zip .
      - name: Upload artifact for app 1
        uses: actions/upload-artifact@v3
        with:
          name: app1
          path: app1/build/app1.zip
      - name: Upload artifact for app 2
        uses: actions/upload-artifact@v3
        with:
          name: app2
          path: app2/build/app2.zip
  deploy-app1:
    runs-on: ubuntu-latest
    needs: build-apps
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: app1
          path: .
      - run: |
          unzip app1.zip
          rm app1.zip
      - name: Logging in to Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "wapp-app1"
          slot-name: "production"
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  deploy-app2:
    runs-on: ubuntu-latest
    needs: build-apps
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: app2
          path: .
      - run: |
          unzip app2.zip
          rm app2.zip
      - name: Logging in to Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "wapp-app2"
          slot-name: "production"
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
